language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - sudo apt-get install libcppunit-dev
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage
  - pip install coveralls
script: ./ensure-zookeeper-env.sh python setup.py nosetests --with-coverage --cover-package=zk_shell
after_script:
  - integration/stop.sh 3.5.0
after_success:
  coveralls
